// <auto-generated />
namespace IAAI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class New_ImageUrl_ToEnableNull : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(New_ImageUrl_ToEnableNull));
        
        string IMigrationMetadata.Id
        {
            get { return "202412241307579_New_ImageUrl_ToEnableNull"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
