// <auto-generated />
namespace IAAI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class CertifiedMember_Add_ImageUrl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CertifiedMember_Add_ImageUrl));
        
        string IMigrationMetadata.Id
        {
            get { return "202412291454032_CertifiedMember_Add_ImageUrl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
