// <auto-generated />
namespace IAAI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Member_Birthday_To_DateTime2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Member_Birthday_To_DateTime2));
        
        string IMigrationMetadata.Id
        {
            get { return "202501091637535_Member_Birthday_To_DateTime2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
